title: Lucas Silva Cabral
description: Desenvolvedor de Software
logo: /Lucas.jpeg

university: Universidade Federal de Pernambuco (UFPE)
gpa: "Média Geral: 8,26"
degree: Bacharelado em Sistema de Informação
focus: Ênfase em Ciências de Dados e Desenvolvimento de Software

theme: jekyll-theme-minimal
